[WIP] MNT-22156 : [Security] Unauthenticated call to internal URLs using RSS feed in Share
Alfresco/share pull request #385
Opened 2021-03-16 22:55 UTC by alexbalmus

Disable RSS dashlet by default + implement flag to enable it on demand

2021-03-18 19:12 UTC, alexbalmus commented on share/src/main/java/org/alfresco/web/scripts/RssDashletStatusWebScript.java
> + * Copyright 2005 - 2020 Alfresco Software Limited.
The copyright year will need to be addressed as part of a separate task for all source files plus the license header text file used by the license check plugin.

2021-03-18 19:28 UTC, skopf requested changes
In this PR, I can only see the logic to hide the RSS dashlet in the UI. But the entire backend logic is still there.
The actual vulnerability however is in the backend logic which performs the requests on behalf of the user.
I assume there is a second part that goes with this commit that blocks the actual backend action? CC: @DavidCervigni

2021-03-18 19:41 UTC, alexbalmus commented
@skopf, the backend logic is in async-rssfeed.get.js which has also been addressed in this PR.
Therefore, a request like the one presented in the Jira ticket description will no longer work (the "feed" JS object will only contain a field "error" with the content "RSS dashlet has been disabled."

2021-03-18 19:46 UTC, skopf approved these changes
Ah, of course. My bad. Should look closer at the path next time.

2021-03-19 10:19 UTC, pieCit87 approved these changes

2021-03-19 13:45 UTC, merged